"""Predictive coding baseline, experiment helpers, and Phase 2 analysis tools."""

from .comparison import ComparisonRunResult, run_benchmark_comparison
from .datasets import load_digits_split, load_fashion_mnist_split
from .pc_budget_tradeoff import PCBudgetTradeoffRunResult, run_pc_budget_tradeoff_study
from .experiment import ExperimentConfig, ExperimentRunResult, run_supervised_experiment
from .fmpc_protocol import (
    FMPCPreparationConfig,
    FMPCPreparationRunResult,
    FMPC_PREPARATION_SCHEMA_VERSION,
    PC_TEACHER_CHECKPOINT_FORMAT,
    load_pc_teacher_checkpoint,
    load_prepared_teacher_runtime,
    resolve_fmpc_teacher_manifest_path,
    save_pc_teacher_checkpoint,
    run_fmpc_v0_preparation,
)
from .fmpc_student_data import (
    FMPCStudentDataset,
    FMPCStudentSplit,
    build_fmpc_student_inputs,
    load_fmpc_student_dataset,
)
from .fmpc_student_normalization import (
    FMPCStudentNormalizationStats,
    fit_fmpc_student_normalization,
)
from .fmpc_student_baselines import (
    ClassMeanDeltaStudent,
    RidgeDeltaStudent,
    RidgeDeltaStudentConfig,
    StandardizedMLPStudent,
    StandardizedMLPStudentConfig,
    identity_delta_prediction,
)
from .fmpc_student import (
    FMPCStudentConfig,
    FMPCStudentRunResult,
    FMPCStudentTransporter,
    evaluate_fmpc_delta_predictions,
    evaluate_fmpc_identity_baseline,
    fmpc_split_evaluation_metrics_payload,
    init_fmpc_student_transporter,
    load_fmpc_student_teacher_runtime,
    prepare_fmpc_student_teacher_references,
    run_fmpc_student_experiment,
)
from .fmpc_student_suite import (
    FMPCStudentSuiteConfig,
    FMPCStudentSuiteRunResult,
    run_fmpc_student_suite,
)
from .fmpc_interval_data import (
    FMPCIntervalBatch,
    FMPCIntervalDataset,
    FMPCIntervalSplit,
    acceptance_schedule_focus_pairs,
    build_fmpc_interval_inputs,
    compute_interval_velocity_target,
    iter_all_interval_blocks,
    iter_balanced_interval_batches,
    iter_mixed_interval_batches,
    iter_weighted_interval_blocks,
    load_fmpc_interval_dataset,
    sample_balanced_interval_batch,
    teacher_step_aligned_rollout_schedules,
)
from .fmpc_interval_features import (
    FMPCIntervalTeacherFeatureBundle,
    FMPCIntervalTeacherFeatureSplitContext,
    FMPCIntervalTeacherStateFeatures,
    FMPCIntervalTeacherStateFeatureTangents,
    FMPCIntervalTeacherTrajectoryFeatures,
    FMPCIntervalTeacherTrajectoryFeatureTangents,
    compute_interval_teacher_state_features,
    compute_interval_teacher_state_feature_tangents,
    prepare_interval_teacher_feature_context,
    precompute_interval_teacher_trajectory_feature_tangents,
    precompute_interval_teacher_trajectory_features,
)
from .fmpc_interval_normalization import (
    FMPCIntervalNormalizationStats,
    fit_fmpc_interval_augmented_normalization,
    fit_fmpc_interval_normalization,
    transform_interval_block_targets,
)
from .fmpc_interval_student import (
    FMPCIntervalRolloutResult,
    FMPCIntervalRolloutAuxiliaryBatches,
    FMPCIntervalSuiteConfig,
    FMPCIntervalSuiteRunResult,
    IntervalAugmentedRidgeStudent,
    IntervalAugmentedRidgeStudentConfig,
    IntervalRidgeStudent,
    IntervalRidgeStudentConfig,
    IntervalStandardizedMLPStudent,
    IntervalStandardizedMLPStudentConfig,
    build_interval_residual_target,
    build_rollout_auxiliary_batches,
    reconstruct_interval_velocity_from_residual,
    rollout_interval_student,
    run_fmpc_interval_suite,
)
from .fmpc_meanflow_jvp import (
    MeanFlowMLPJVPResult,
    build_meanflow_input_tangent,
    forward_mlp_with_jvp,
)
from .fmpc_meanflow_student import (
    FMPCMeanFlowSuiteConfig,
    FMPCMeanFlowSuiteRunResult,
    MeanFlowMLPStudent,
    MeanFlowMLPStudentConfig,
    MeanFlowTwoBranchResidualStudent,
    MeanFlowTwoBranchStudentConfig,
    build_meanflow_full_identity_target_raw,
    build_meanflow_identity_target,
    reconstruct_meanflow_velocity,
    run_fmpc_meanflow_suite,
)
from .fmpc_tf1 import (
    FMPCTF1Config,
    FMPCTF1EpochSnapshot,
    FMPCTF1RunResult,
    build_tf1_baseline_comparable_config,
    build_tf1_baseline_working_default_config,
    build_tf1_epoch_selection_diagnostics,
    build_tf1_mechanism_smoke_config,
    build_tf1_preset_config,
    run_fmpc_tf1_experiment,
)
from .fmpc_tf1_suite import (
    FMPCTF1SuiteConfig,
    FMPCTF1SuiteRunResult,
    run_fmpc_tf1_suite,
)
from .fmpc_tf1_selection_suite import (
    FMPCTF1SelectionSuiteConfig,
    FMPCTF1SelectionSuiteRunResult,
    run_fmpc_tf1_selection_suite,
)
from .fmpc_tf1_gate_coverage_suite import (
    FMPCTF1GateCoverageSuiteConfig,
    FMPCTF1GateCoverageSuiteRunResult,
    run_fmpc_tf1_gate_coverage_suite,
)
from .fmpc_tf1_multiseed_suite import (
    FMPCTF1MultiSeedSuiteConfig,
    FMPCTF1MultiSeedSuiteRunResult,
    run_fmpc_tf1_multiseed_suite,
)
from .fmpc_tf1_selector_policy_suite import (
    FMPCTF1SelectorPolicySuiteConfig,
    FMPCTF1SelectorPolicySuiteRunResult,
    run_fmpc_tf1_selector_policy_suite,
)
from .fmpc_tf1_default_adoption_suite import (
    FMPCTF1DefaultAdoptionSuiteConfig,
    FMPCTF1DefaultAdoptionSuiteRunResult,
    run_fmpc_tf1_default_adoption_suite,
)
from .fmpc_tf1_external_comparison_suite import (
    FMPCTF1ExternalComparisonSuiteConfig,
    FMPCTF1ExternalComparisonSuiteRunResult,
    run_fmpc_tf1_external_comparison_suite,
)
from .fmpc_tf1_accuracy_tuning_suite import (
    FMPCTF1AccuracyTuningSuiteConfig,
    FMPCTF1AccuracyTuningSuiteRunResult,
    run_fmpc_tf1_accuracy_tuning_suite,
)
from .fmpc_tf2 import (
    FMPCTF2Config,
    FMPCTF2EpochSnapshot,
    FMPCTF2RunResult,
    TF2PresetName,
    TF2MicroStepPlan,
    build_tf2_canonical_config,
    build_tf2_corrective_transport_default_config,
    build_tf2_corrective_transport_terminal_angleclip_default_config,
    build_tf2_preset_config,
    run_fmpc_tf2_experiment,
)
from .fmpc_tf2_suite import (
    FMPCTF2SuiteConfig,
    FMPCTF2SuiteRunResult,
    run_fmpc_tf2_suite,
)
from .fmpc_tf2_default_adoption_suite import (
    FMPCTF2DefaultAdoptionSuiteConfig,
    FMPCTF2DefaultAdoptionSuiteRunResult,
    run_fmpc_tf2_default_adoption_suite,
)
from .fmpc_tf2_mainline_adoption_suite import (
    FMPCTF2MainlineAdoptionSuiteConfig,
    FMPCTF2MainlineAdoptionSuiteRunResult,
    run_fmpc_tf2_mainline_adoption_suite,
)
from .fmpc_tf2_identity_semantics_suite import (
    FMPCTF2IdentitySemanticsSuiteConfig,
    FMPCTF2IdentitySemanticsSuiteRunResult,
    run_fmpc_tf2_identity_semantics_suite,
)
from .fmpc_tf2_attribution_suite import (
    FMPCTF2AttributionSuiteConfig,
    FMPCTF2AttributionSuiteRunResult,
    run_fmpc_tf2_attribution_suite,
)
from .fmpc_tf2_microstep_horizon_suite import (
    FMPCTF2MicrostepHorizonSuiteConfig,
    FMPCTF2MicrostepHorizonSuiteRunResult,
    run_fmpc_tf2_microstep_horizon_suite,
)
from .fmpc_tf2_curriculum_suite import (
    FMPCTF2CurriculumSuiteConfig,
    FMPCTF2CurriculumSuiteRunResult,
    run_fmpc_tf2_curriculum_suite,
)
from .fmpc_tf2_bootstrap_fidelity_suite import (
    FMPCTF2BootstrapFidelitySuiteConfig,
    FMPCTF2BootstrapFidelitySuiteRunResult,
    run_fmpc_tf2_bootstrap_fidelity_suite,
)
from .fmpc_tf2_bootstrap_source_bias_suite import (
    FMPCTF2BootstrapSourceBiasSuiteConfig,
    FMPCTF2BootstrapSourceBiasSuiteRunResult,
    run_fmpc_tf2_bootstrap_source_bias_suite,
)
from .fmpc_tf2b_interleaving_suite import (
    FMPCTF2BInterleavingSuiteConfig,
    FMPCTF2BInterleavingSuiteRunResult,
    run_fmpc_tf2b_interleaving_suite,
)
from .inference import TeacherInferenceExport, run_teacher_inference_export
from .layers import PCLayerParams, init_mlp_layers
from .metrics import (
    energy_gap_to_teacher,
    hidden_state_l2_distance,
    hidden_state_rms_gap,
    state_update_direction_cosine,
    summarize_teacher_reference_metrics,
    update_direction_cosine,
)
from .mlp_baseline import MLPNetwork, MLPLayerParams, init_mlp_baseline_layers
from .minibatch import iter_minibatches
from .real_mlp import RealMLPConfig, RealMLPRunResult, run_digits_mlp_experiment
from .real_pc_inference_baselines import (
    RealPCInferenceBaselineCandidate,
    RealPCInferenceBaselineStudyConfig,
    RealPCInferenceBaselineStudyResult,
    run_real_pc_inference_baseline_study,
)
from .real_pc import RealPCConfig, RealPCRunResult, run_digits_pc_experiment, run_real_pc_experiment
from .state_io import flatten_hidden_states, unflatten_hidden_states
from .phase2g1_boundary_check import (
    Phase2G1BoundaryCheckRunResult,
    run_phase2g1_boundary_check,
)
from .pc_joint_search import PCJointSearchRunResult, run_pc_joint_search
from .models import PCNetwork
from .pc_diagnostics import PCDiagnosticsRunResult, run_pc_diagnostics_study
from .pc_multiseed import PCMultiSeedRunResult, run_pc_multiseed_study
from .pc_sensitivity import PCSensitivityRunResult, run_pc_sensitivity_study

__all__ = [
    "ComparisonRunResult",
    "ExperimentConfig",
    "ExperimentRunResult",
    "FMPCPreparationConfig",
    "FMPC_PREPARATION_SCHEMA_VERSION",
    "FMPCPreparationRunResult",
    "FMPCIntervalBatch",
    "FMPCIntervalDataset",
    "FMPCIntervalNormalizationStats",
    "FMPCIntervalRolloutResult",
    "FMPCIntervalRolloutAuxiliaryBatches",
    "FMPCIntervalSplit",
    "FMPCIntervalSuiteConfig",
    "FMPCIntervalSuiteRunResult",
    "FMPCMeanFlowSuiteConfig",
    "FMPCMeanFlowSuiteRunResult",
    "FMPCTF1Config",
    "FMPCTF1EpochSnapshot",
    "FMPCTF1GateCoverageSuiteConfig",
    "FMPCTF1GateCoverageSuiteRunResult",
    "FMPCTF1DefaultAdoptionSuiteConfig",
    "FMPCTF1DefaultAdoptionSuiteRunResult",
    "FMPCTF1ExternalComparisonSuiteConfig",
    "FMPCTF1ExternalComparisonSuiteRunResult",
    "FMPCTF1AccuracyTuningSuiteConfig",
    "FMPCTF1AccuracyTuningSuiteRunResult",
    "FMPCTF2Config",
    "FMPCTF2BInterleavingSuiteConfig",
    "FMPCTF2BInterleavingSuiteRunResult",
    "FMPCTF2AttributionSuiteConfig",
    "FMPCTF2AttributionSuiteRunResult",
    "FMPCTF2DefaultAdoptionSuiteConfig",
    "FMPCTF2DefaultAdoptionSuiteRunResult",
    "FMPCTF2MainlineAdoptionSuiteConfig",
    "FMPCTF2MainlineAdoptionSuiteRunResult",
    "FMPCTF2EpochSnapshot",
    "FMPCTF2RunResult",
    "FMPCTF2SuiteConfig",
    "FMPCTF2SuiteRunResult",
    "FMPCTF1MultiSeedSuiteConfig",
    "FMPCTF1MultiSeedSuiteRunResult",
    "FMPCTF1RunResult",
    "FMPCTF1SelectorPolicySuiteConfig",
    "FMPCTF1SelectorPolicySuiteRunResult",
    "FMPCTF1SelectionSuiteConfig",
    "FMPCTF1SelectionSuiteRunResult",
    "FMPCTF1SuiteConfig",
    "FMPCTF1SuiteRunResult",
    "FMPCIntervalTeacherFeatureBundle",
    "FMPCIntervalTeacherFeatureSplitContext",
    "FMPCIntervalTeacherStateFeatures",
    "FMPCIntervalTeacherStateFeatureTangents",
    "FMPCIntervalTeacherTrajectoryFeatures",
    "FMPCIntervalTeacherTrajectoryFeatureTangents",
    "FMPCStudentConfig",
    "FMPCStudentDataset",
    "FMPCStudentNormalizationStats",
    "FMPCStudentRunResult",
    "FMPCStudentSplit",
    "FMPCStudentSuiteConfig",
    "FMPCStudentSuiteRunResult",
    "FMPCStudentTransporter",
    "ClassMeanDeltaStudent",
    "IntervalAugmentedRidgeStudent",
    "IntervalAugmentedRidgeStudentConfig",
    "IntervalRidgeStudent",
    "IntervalRidgeStudentConfig",
    "IntervalStandardizedMLPStudent",
    "IntervalStandardizedMLPStudentConfig",
    "MeanFlowMLPJVPResult",
    "MeanFlowMLPStudent",
    "MeanFlowMLPStudentConfig",
    "MeanFlowTwoBranchResidualStudent",
    "MeanFlowTwoBranchStudentConfig",
    "MLPLayerParams",
    "MLPNetwork",
    "PCBudgetTradeoffRunResult",
    "PC_TEACHER_CHECKPOINT_FORMAT",
    "PCJointSearchRunResult",
    "Phase2G1BoundaryCheckRunResult",
    "PCDiagnosticsRunResult",
    "PCMultiSeedRunResult",
    "PCLayerParams",
    "PCSensitivityRunResult",
    "PCNetwork",
    "RealMLPConfig",
    "RealMLPRunResult",
    "RealPCInferenceBaselineCandidate",
    "RealPCInferenceBaselineStudyConfig",
    "RealPCInferenceBaselineStudyResult",
    "RealPCConfig",
    "RealPCRunResult",
    "TeacherInferenceExport",
    "TF2PresetName",
    "TF2MicroStepPlan",
    "acceptance_schedule_focus_pairs",
    "build_fmpc_interval_inputs",
    "build_meanflow_identity_target",
    "build_meanflow_input_tangent",
    "build_tf1_baseline_comparable_config",
    "build_tf1_baseline_working_default_config",
    "build_tf1_epoch_selection_diagnostics",
    "build_tf1_mechanism_smoke_config",
    "build_tf1_preset_config",
    "build_tf2_canonical_config",
    "build_tf2_corrective_transport_default_config",
    "build_tf2_corrective_transport_terminal_angleclip_default_config",
    "build_tf2_preset_config",
    "build_interval_residual_target",
    "build_fmpc_student_inputs",
    "build_meanflow_full_identity_target_raw",
    "compute_interval_velocity_target",
    "compute_interval_teacher_state_features",
    "compute_interval_teacher_state_feature_tangents",
    "energy_gap_to_teacher",
    "evaluate_fmpc_delta_predictions",
    "evaluate_fmpc_identity_baseline",
    "flatten_hidden_states",
    "fit_fmpc_interval_augmented_normalization",
    "fit_fmpc_interval_normalization",
    "fit_fmpc_student_normalization",
    "fmpc_split_evaluation_metrics_payload",
    "hidden_state_l2_distance",
    "hidden_state_rms_gap",
    "identity_delta_prediction",
    "init_fmpc_student_transporter",
    "init_mlp_layers",
    "init_mlp_baseline_layers",
    "iter_all_interval_blocks",
    "iter_balanced_interval_batches",
    "iter_mixed_interval_batches",
    "iter_weighted_interval_blocks",
    "iter_minibatches",
    "load_fmpc_interval_dataset",
    "load_fmpc_student_teacher_runtime",
    "load_digits_split",
    "load_pc_teacher_checkpoint",
    "load_prepared_teacher_runtime",
    "load_fmpc_student_dataset",
    "load_fashion_mnist_split",
    "prepare_fmpc_student_teacher_references",
    "prepare_interval_teacher_feature_context",
    "precompute_interval_teacher_trajectory_features",
    "precompute_interval_teacher_trajectory_feature_tangents",
    "resolve_fmpc_teacher_manifest_path",
    "reconstruct_meanflow_velocity",
    "reconstruct_interval_velocity_from_residual",
    "run_benchmark_comparison",
    "run_digits_mlp_experiment",
    "run_digits_pc_experiment",
    "run_fmpc_v0_preparation",
    "run_fmpc_interval_suite",
    "run_fmpc_meanflow_suite",
    "run_fmpc_tf1_experiment",
    "run_fmpc_tf1_default_adoption_suite",
    "run_fmpc_tf1_accuracy_tuning_suite",
    "run_fmpc_tf2_mainline_adoption_suite",
    "run_fmpc_tf1_external_comparison_suite",
    "run_fmpc_tf1_gate_coverage_suite",
    "run_fmpc_tf1_multiseed_suite",
    "run_fmpc_tf1_selector_policy_suite",
    "run_fmpc_tf1_selection_suite",
    "run_fmpc_tf1_suite",
    "run_fmpc_tf2_experiment",
    "run_fmpc_tf2_default_adoption_suite",
    "run_fmpc_tf2_attribution_suite",
    "run_fmpc_tf2_bootstrap_fidelity_suite",
    "run_fmpc_tf2_bootstrap_source_bias_suite",
    "run_fmpc_tf2b_interleaving_suite",
    "FMPCTF2BootstrapFidelitySuiteConfig",
    "FMPCTF2BootstrapFidelitySuiteRunResult",
    "FMPCTF2BootstrapSourceBiasSuiteConfig",
    "FMPCTF2BootstrapSourceBiasSuiteRunResult",
    "run_fmpc_tf2_suite",
    "build_rollout_auxiliary_batches",
    "run_fmpc_student_experiment",
    "run_fmpc_student_suite",
    "run_real_pc_inference_baseline_study",
    "run_real_pc_experiment",
    "run_teacher_inference_export",
    "run_phase2g1_boundary_check",
    "run_pc_budget_tradeoff_study",
    "run_pc_joint_search",
    "run_pc_diagnostics_study",
    "run_pc_multiseed_study",
    "run_pc_sensitivity_study",
    "run_supervised_experiment",
    "save_pc_teacher_checkpoint",
    "RidgeDeltaStudent",
    "RidgeDeltaStudentConfig",
    "StandardizedMLPStudent",
    "StandardizedMLPStudentConfig",
    "state_update_direction_cosine",
    "summarize_teacher_reference_metrics",
    "sample_balanced_interval_batch",
    "teacher_step_aligned_rollout_schedules",
    "forward_mlp_with_jvp",
    "transform_interval_block_targets",
    "unflatten_hidden_states",
    "update_direction_cosine",
    "rollout_interval_student",
]
